name: CI

on:
  push:
    branches:
    - master
    - 'releases/**'
  pull_request:
    branches:
    - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build with dotnet
      run: dotnet build prime --configuration Release
    
    - name: Run tests
      run: dotnet test prime
